language: objective-c
xcode_project: Socket.IO-Client-Swift.xcodeproj # path to your xcodeproj folder
xcode_scheme: SocketIO-iOS
osx_image: xcode7
script: xctool -project Socket.IO-Client-Swift.xcodeproj -scheme SocketIO-iOS build  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO