language: objective-c
xcode_project: Socket.IO-Client-Swift.xcodeproj # path to your xcodeproj folder
xcode_scheme: SocketIO-iOS
osx_image: xcode7
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
script: xctool -project Socket.IO-Client-Swift.xcodeproj -scheme SocketIO-iOS -sdk iphonesimulator build test  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
before_install: 
install: cd Socket.IO-Test-Server/ && npm install && cd .. && node Socket.IO-Test-Server/main.js &
cache:
  directories:
    - Socket.IO-Test-Server/node_modules